# Minecraft Stoneblock4 Stack Configuration for Docker Swarm
networks:
  schub:
    external: true

# Secrets
secrets:
  MINECRAFT_RCON_PASSWORD:
    external: true
  MINECRAFT_CF_API_KEY:
    external: true

# Log Configuration
x-logging:
  &default-logging
  driver: "json-file"
  options:
    tag: "{{.Name}}"

# Container Configuration
services:
  gaming-minecraft-terrafirmacraft4:
    image: itzg/minecraft-server:latest
    networks:
      - schub
    ports:
      - "25982:25565"
    volumes:
      - minecraft_terrafirmacraft4_data:/data
      - minecraft_terrafirmacraft4_modpacks:/modpacks
    secrets:
      - MINECRAFT_RCON_PASSWORD
    environment:
      EULA: "TRUE"
      TYPE: CURSEFORGE
      CF_MODPACK_ZIP: "/modpacks/HTFC4-0.4.2.zip"
      MEMORY: "16G"
      ENABLE_RCON: "true"
      RCON_PASSWORD_FILE: /run/secrets/MINECRAFT_RCON_PASSWORD
      RCON_PORT: "25875"
      ALLOW_FLIGHT: "true"
      ENABLE_COMMAND_BLOCK: "true"
      CF_SERVER_MOD : "HTFC4-0.4.2.zip"
    logging: *default-logging
    deploy:
      resources:
        limits:
          memory: 20G
      placement:
        constraints:
          - node.labels.name == loki

volumes:
  minecraft_terrafirmacraft4_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/volume/Minecraft/TerraFirmaCraft4/Data
  minecraft_terrafirmacraft4_modpacks:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/volume/Minecraft/TerraFirmaCraft4/Modpacks
