; -> /mnt/volume/Samba/smb.conf sur loki. Chemins vus du conteneur (/mnt -> /shares).

[global]
   workgroup = WORKGROUP
   server string = loki
   security = user
   map to guest = Never
   server min protocol = SMB2_10
   load printers = no
   printing = bsd
   printcap name = /dev/null
   disable spoolss = yes

[volume]
   path = /shares/volume
   valid users = pisel
   read only = no
   browseable = yes
   create mask = 0664
   directory mask = 0775
