#Principale Network Configuration

networks:
  default:
    name: nextcloud_default
    driver: bridge

#Log Configuration

x-logging:
  &default-logging
  driver: "json-file"
  options:
    tag: "{{.Name}}"

#Container Configuration

services:
  nextcloud:
    container_name: ${NEXTCLOUD_CONTAINER_NAME}
    image: nextcloud
    ports:
      - "${NEXTCLOUD_EXTERNAL_PORT}:${NEXTCLOUD_INTERNAL_PORT}"
    volumes:
      - ${ROOT_DATA_DIR}/${STACK_NAME}/${DATA_PATH}:/var/www/html
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - OVERWRITECLIURL=${URL_IN_DNS}
      - OVERWRITEPROTOCOL=https
      - TRUSTED_PROXIES="*"
      - PHP_UPLOAD_LIMIT=100G
      - PHP_MEMORY_LIMIT=100G
    depends_on: 
      - nextcloud_db
    logging: *default-logging 
    restart: always

  nextcloud_db:
    container_name: ${NEXTCLOUD_DB_CONTAINER_NAME}
    image: mariadb
    volumes:
      - ${ROOT_DATA_DIR}/${STACK_NAME}/${DATABASE_PATH}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    logging: *default-logging
    restart: always
