version: '3.9'

services:
  postgres:
    container_name: db
    image: "postgres:14.4"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
      #- ./sql:/docker-entrypoint-initdb.d/:ro # turn it on, if you need run init DB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"

  pgadmin:
      container_name: pgadmin
      image: "dpage/pgadmin4:5.1"
      environment:
        PGADMIN_DEFAULT_EMAIL: postgres@domain.local
        PGADMIN_DEFAULT_PASSWORD: postgres
      ports:
        - "5050:80"

  auth:
    image: quay.io/keycloak/keycloak
    ports:
      - "9000:9000"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --import-realm
    volumes:
      - /home/keycloak/realm.json:/opt/keycloak/data/import/realm.json

  rabbitmq:
    container_name : rabbitmq
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672'

  portainer:
    container_name : portainer
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

#  back:
#    container_name: schub_back
#    build: ./../Back
#    ports:
#      - "8090:8090"
#    restart: on-failure
#    volumes:
#      - .m2:/root/.m2
#    stdin_open: true
#    tty: true

  front:
    container_name: schub_front
    build: ./../Front
    ports:
      - "8080:8080"
    restart: on-failure
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true


  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
    deploy:
      resources:
        limits:
          memory: 2048M
    volumes:
      - "./minecraft/minecraft_data:/data"

  server-manager:
    container_name: assetto-server-manager
    image: seejy/assetto-server-manager:latest
    ports:
      # the port that the server manager runs on
      - "8772:8772"
      # the port that the assetto server runs on (may vary depending on your configuration inside server manager)
      - "9600:9600"
      - "9600:9600/udp"
      # the port that the assetto server HTTP API runs on.
      - "8081:8081"
    # you may also wish to bind your configured UDP plugin ports here.
    volumes:
      # volume mount the entire server install so that
      # content etc persists across restarts
      - assetto/server-install:/home/assetto/server-manager/assetto

      # volume mount the config
      - assetto/config.yml:/home/assetto/server-manager/config.yml

  satisfactory-server:
    container_name: 'satisfactory-server'
    hostname: 'satisfactory-server'
    image: 'wolveix/satisfactory-server:latest'
    ports:
      - '7777:7777/udp'
      - '15000:15000/udp'
      - '15777:15777/udp'
    volumes:
      - './satisfactory/config:/config'
    environment:
      - MAXPLAYERS=4
      - PGID=1000
      - PUID=1000
      - STEAMBETA=false
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 4G

networks:
  default:
    name: schub_network

volumes:
  postgres_data:
  data:

