version: '3.8'

# Volumes

volumes:
  organizr_config:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume/Organizr/Config
      o: bind

# Log Configuration

x-logging:
  &default-logging
  driver: "json-file"
  options:
    tag: "{{.Name}}"

# Services

services:
  organizr:
    image: organizr/organizr@sha256:1ce319d73cdfd2666ec7ef21e15907531fabc8a6f333c4ac61e2b2e9d2d162f5
    networks:
      - schub
    ports:
      - 8080:80
    volumes:
      - organizr_config:/config
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
    logging: *default-logging
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.name == dynamis

# Networks

networks:
  schub:
    external: true
