#Principale Network Configuration

networks:
  default:
    name: schub_network
    ipam:
      config:
        - subnet: 172.20.0.0/16

#Log Configuration

x-logging:
  &default-logging
  driver: "json-file"
  options:
    tag: "{{.Name}}"

#Container Configuration

services:

  host-front: 
    container_name: ${FRONT_CONTAINER_NAME} 
    ports: 
      - ${FRONT_EXTERNAL_PORT}:${FRONT_INTERNAL_PORT} 
    env_file: 
      - ../.env 
    build: ${FRONT_BUILD_PATH} 
    hostname: front 
    stdin_open: true 
    tty: true 
    logging: *default-logging 
    restart: unless-stopped
    

  host-bot: 
    container_name: ${DISCORD_BOT_CONTAINER_NAME} 
    image: thomasschultzschub/discord-bot:latest 
    env_file: 
      - bot.env  
    logging: *default-logging
    depends_on:
      - host-mongo 
    restart: unless-stopped

  host-mongo: 
    container_name: ${MONGODB_CONTAINER_NAME} 
    image: mongo:latest 
    volumes:
      - ${ROOT_PROJECT_DATA_DIR}/${MONGODB_PATH}:/data/db 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME} 
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    logging: *default-logging 
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: ${SONARR_CONTAINER_NAME}
    ports:
      - ${SONARR_PORT}:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ${ROOT_PROJECT_DATA_DIR}/${SONARR_CONFIG_PATH}:/config
      - ${PLEX_MOVIE_SAVE_PATH}/${SONARR_MEDIA_PATH}:/tv
      - ${PLEX_MOVIE_SAVE_PATH}/${SONARR_DOWNLOAD_PATH}:/downloads
    restart: unless-stopped
    logging: *default-logging 

  radarr: 
    image: linuxserver/radarr 
    container_name: ${RADARR_CONTAINER_NAME} 
    ports:  
      - ${RADARR_PORT}:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ${ROOT_PROJECT_DATA_DIR}/${RADARR_CONFIG_PATH}:/config
      - ${PLEX_MOVIE_SAVE_PATH}/${RADARR_MEDIA_PATH}:/movie
      - ${PLEX_MOVIE_SAVE_PATH}/${RADARR_DOWNLOAD_PATH}:/downloads
    restart: unless-stopped
    logging: *default-logging 


  jellyfin: 
    image: jellyfin/jellyfin 
    container_name: ${JELLYFIN_CONTAINER_NAME}
    ports:
      - ${JELLYFIN_PORT}:8096
    volumes:
      - ${ROOT_PROJECT_DATA_DIR}/${JELYFFIN_CONFIG_PATH}/config:/config
      - ${ROOT_PROJECT_DATA_DIR}/${JELYFFIN_CONFIG_PATH}/cache:/cache
      - ${PLEX_MOVIE_SAVE_PATH}/movie:/media:ro
    restart: unless-stopped
    logging: *default-logging 
    environment:
      - TZ=Europe/Paris
