version: "3.9"

networks:
  default:
    name: schub_network
    external: true
  private:
    name: schub_private_network
    driver: bridge

services:
  host-plex:
    container_name: ${PLEX_CONTAINER_NAME}
    image: lscr.io/linuxserver/plex:latest
    env_file:
      - ../.env
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${ROOT_PROJECT_DATA_DIR}/${PLEX_CONFIG_SAVE_PATH}:/config
      - ${ROOT_PROJECT_DATA_DIR}/${PLEX_TV_SAVE_PATH}:/tv
      - ${PLEX_MOVIE_SAVE_PATH}:/movies
    restart: unless-stopped

  host-front:
    container_name: ${FRONT_CONTAINER_NAME}
    env_file:
      - ../.env
    build: ${FRONT_BUILD_PATH}
    hostname: front
    ports:
      - ${FRONT_EXTERNAL_PORT}:${FRONT_INTERNAL_PORT}
    stdin_open: true
    tty: true
    restart: unless-stopped