# Minecraft Stoneblock4 Stack Configuration for Docker Swarm
networks:
  schub:
    external: true

# Secrets
secrets:
  MINECRAFT_RCON_PASSWORD:
    external: true
  MINECRAFT_CF_API_KEY:
    external: true

# Log Configuration
x-logging:
  &default-logging
  driver: "json-file"
  options:
    tag: "{{.Name}}"

# Container Configuration
services:
  gaming-minecraft-stoneblock4:
    image: itzg/minecraft-server:stable-java21-jdk
    networks:
      - schub
    ports:
      - "25980:25565"
    volumes:
      - minecraft_stoneblock4_data:/data
    secrets:
      - MINECRAFT_RCON_PASSWORD
      - MINECRAFT_CF_API_KEY
    environment:
      EULA: "TRUE"
      ENABLE_RCON: "true"
      RCON_PASSWORD_FILE: /run/secrets/MINECRAFT_RCON_PASSWORD
      RCON_PORT: "25875"
      TYPE: AUTO_CURSEFORGE
      VERSION: "1.21.1"
      CF_SLUG: ftb-stoneblock-4
      CF_API_KEY_FILE: /run/secrets/MINECRAFT_CF_API_KEY
      MEMORY: "20G"
      ALLOW_FLIGHT: "true"
      ENABLE_COMMAND_BLOCK: "true"
      CF_FILENAME_MATCHER: 1.5.0
      FORGE_VERSION: "47.2.0"
    logging: *default-logging
    deploy:
      resources:
        limits:
          memory: 24G
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.name == loki

volumes:
  minecraft_stoneblock4_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/volume/Minecraft/Stoneblock4
