#Principale Network Configuration

networks:
  default:
    name: Monitoring
    external: true  

#Log Configuration

x-logging:
  &default-logging
  driver: "json-file"
  options:
    tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

#Container Configuration

services:

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ${ROOT_PROJECT_DATA_DIR}/${PROMETHEUS_PATH}/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    logging: *default-logging
    restart: unless-stopped

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ${ROOT_PROJECT_DATA_DIR}/${GRAFANA_PATH}:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    logging: *default-logging
    restart: unless-stopped

  loki:
    container_name: loki
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    volumes:
      - ${ROOT_PROJECT_DATA_DIR}/${LOKI_PATH}/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    logging: *default-logging
    restart: unless-stopped

  promtail:
    container_name: ${PROMTAIL_CONTAINER_NAME}
    image: grafana/promtail:2.9.0
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log
      - ${ROOT_PROJECT_DATA_DIR}/${PROMTAIL_PATH}/docker-config.yml:/etc/promtail/docker-config.yml
    command: -config.file=/etc/promtail/docker-config.yml
    logging: *default-logging
    restart: unless-stopped