#Principale Network Configuration

networks:
  default:
    name: schub_network
    ipam:
      config:
        - subnet: 172.20.0.0/16

#Log Configuration

x-logging:
  &default-logging
  driver: "json-file"
  options:
    tag: "{{.Name}}"

#Container Configuration

services:

  sonarr:
    image: linuxserver/sonarr
    container_name: ${SONARR_CONTAINER_NAME}
    ports:
      - ${SONARR_EXTERNAL_PORT}:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ${ROOT_PROJECT_DATA_DIR}/${SONARR_CONFIG_PATH}:/config
      - ${MOVIE_SAVE_PATH}/${SONARR_MEDIA_PATH}:/tv
      - ${MOVIE_SAVE_PATH}/${DOWNLOAD_PATH}:/downloads
    restart: unless-stopped
    logging: *default-logging 

  radarr: 
    image: linuxserver/radarr 
    container_name: ${RADARR_CONTAINER_NAME} 
    ports:  
      - ${RADARR_EXTERNAL_PORT}:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ${ROOT_PROJECT_DATA_DIR}/${RADARR_CONFIG_PATH}:/config
      - ${MOVIE_SAVE_PATH}/${RADARR_MEDIA_PATH}:/movie
      - ${MOVIE_SAVE_PATH}/${DOWNLOAD_PATH}:/downloads
    restart: unless-stopped
    logging: *default-logging 


  jellyfin: 
    image: jellyfin/jellyfin 
    container_name: ${JELLYFIN_CONTAINER_NAME}
    environment:
      - TZ=Europe/Paris
    ports:
      - ${JELLYFIN_EXTERNAL_PORT}:8096
    volumes:
      - ${ROOT_PROJECT_DATA_DIR}/${JELYFFIN_CONFIG_PATH}/config:/config
      - ${ROOT_PROJECT_DATA_DIR}/${JELYFFIN_CONFIG_PATH}/cache:/cache
      - ${MOVIE_SAVE_PATH}/media:/media:ro
    restart: unless-stopped
    logging: *default-logging 

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: ${FILE_BROWSER_CONTAINER_NAME}
    ports:
      -  ${FILE_BROWSER_EXTERNAL_PORT}:80  # Change le port si nécessaire
    volumes:
      - ${MOVIE_SAVE_PATH}/${DOWNLOAD_PATH}:/srv           # Dossier des téléchargements (Radarr)
      - ${ROOT_PROJECT_DATA_DIR}/${FILE_BROWSER_CONFIG_PATH}/config:/config        # Dossier de config File Browser
      - ${ROOT_PROJECT_DATA_DIR}/${FILE_BROWSER_CONFIG_PATH}/database:/database    # DB utilisateurs/prefs
    restart: unless-stopped
    environment:
      - PUID=1000   # Remplace avec ton UID
      - PGID=1000   # Remplace avec ton GID
