#Principale Network Configuration

networks:
  schub:
    external: true


#Log Configuration

x-logging:
  &default-logging
  driver: "json-file"
  options:
    tag: "{{.Name}}"

#Container Configuration

services:

  gaming-palworld-ptite-fesse:
    image: thijsvanloef/palworld-server-docker@sha256:be3ad49e373045a7b60478fd8b7f7411c1e293713dfa4733e563e798f276d688
    networks:
      - schub
    ports:
      - 8212:8212/udp
      - 27016:27016/udp
    volumes:
      - palworld_data_ptite_fesse:/palworld/
    stop_grace_period: 30s # Set to however long you are willing to wait for the container to gracefully stop
    environment:
      AUTO_UPDATE_ENABLED: "true"
      PUID: 1000
      PGID: 1000
      PORT: "8212"
      QUERY_PORT: "27016"
      PLAYERS: "16"
      SERVER_PASSWORD: "${SERVER_PASSWORD}"
      MULTITHREADING: "true"
      RCON_ENABLED: "true"
      RCON_PORT: "25576"
      TZ: "UTC"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
      PAL_EGG_DEFAULT_HATCHING_TIME: "0.000000"
      COMMUNITY: "true"
      SERVER_NAME: "ptite fesse"
      SERVER_DESCRIPTION: "palworld-server-docker by Pisel"
      BASE_CAMP_MAX_NUM: "200"
      AUTO_REBOOT_ENABLED: "true"
      AUTO_REBOOT_WARN_MINUTES: "10"
      AUTO_REBOOT_EVEN_IF_PLAYERS_ONLINE: "false"
      AUTO_REBOOT_CRON_EXPRESSION: "0 */4 * * *"
      MAX_BUILDING_LIMIT_NUM : "0"
      BASE_CAMP_WORKER_MAX_NUM : "50"
      PLAYER_STAMINA_DECREASE_RATE : "0.300000"
      PAL_CAPTURE_RATE : "2.000000"
      EXP_RATE : "2.000000"
    logging: *default-logging
    deploy:
      resources:
        limits:
          memory: 12G
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.name == loki


# Volume

volumes:
  palworld_data_ptite_fesse:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/volume/Palworld/Palworld_PtiteFesse
