version: '3.8'

# Volumes

volumes:
  nextcloud_data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/data/NextCloud_Schub
      o: bind
  nextcloud_database:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume/Nextcloud/Database
      o: bind

# Secrets

secrets:
  NEXTCLOUD_DB_PASSWORD:
    external: true
  NEXTCLOUD_DB_ROOT_PASSWORD:
    external: true

# Log Configuration

x-logging:
  &default-logging
  driver: "json-file"
  options:
    tag: "{{.Name}}"

# Services

services:
  nextcloud:
    image: nextcloud:33.0.8
    networks:
      - schub
    volumes:
      - nextcloud_data:/var/www/html
    secrets:
      - NEXTCLOUD_DB_PASSWORD
    environment:
      MYSQL_HOST: nextcloud_db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD_FILE: /run/secrets/NEXTCLOUD_DB_PASSWORD
      OVERWRITECLIURL: nextcloud.schultz-thomas.fr
      OVERWRITEPROTOCOL: https
      TRUSTED_PROXIES: "*"
      PHP_UPLOAD_LIMIT: 100G
      PHP_MEMORY_LIMIT: 100G
    logging: *default-logging 
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.name == dynamis

  collabora:
    image: collabora/code:26.04.3.1.1
    networks:
      - schub
    environment:
      domain: nextcloud\.schultz-thomas\.fr
      server_name: collabora.schultz-thomas.fr
      DONT_GEN_SSL_CERT: "YES"
      extra_params: --o:ssl.enable=false --o:ssl.termination=true --o:logging.level=warning
    logging: *default-logging
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.name == dynamis

  nextcloud_db:
    image: mariadb:12.3.3
    networks:
      - schub
    volumes:
      - nextcloud_database:/var/lib/mysql
    secrets:
      - NEXTCLOUD_DB_PASSWORD
      - NEXTCLOUD_DB_ROOT_PASSWORD
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/NEXTCLOUD_DB_ROOT_PASSWORD
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD_FILE: /run/secrets/NEXTCLOUD_DB_PASSWORD
    logging: *default-logging
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.name == dynamis

# Networks

networks:
  schub:
    external: true