#Principale Network Configuration

networks:
  default:
    name: schub_network
    external: true  
    ipam:
      config:
        - subnet: 172.20.0.0/16

#Log Configuration

x-logging:
  &default-logging
  driver: "json-file"
  options:
    tag: "{{.Name}}"

#Container Configuration

services:

  gaming-minecraft-ftb:
    container_name: ${MINECRAFT_REVELATION_CONTAINER_NAME}
    image: itzg/minecraft-server:java8-multiarch
    ports:
      - ${MINECRAFT_REVELATION_PORT_EXTERNAL}:${MINECRAFT_REVELATION_PORT_INTERNAL}
    volumes:
      - ${ROOT_PROJECT_DATA_DIR}/${MINECRAFT_REVELATION_SAVE_PATH}:/data
    deploy:
      resources:
        limits:
          memory: 4096M
    env_file:
      - ./ftb.env
    logging: *default-logging
    restart: unless-stopped

  gaming-minecraft-miam:
    container_name: ${MINECRAFT_PAPER_CONTAINER_NAME}
    image: itzg/minecraft-server
    ports:
      - ${MINECRAFT_PAPER_PORT_EXTERNAL}:${MINECRAFT_PAPER_PORT_INTERNAL}
    volumes:
      - ${ROOT_PROJECT_DATA_DIR}/${MINECRAFT_PAPER_SAVE_PATH}:/data
    deploy:
      resources:
        limits:
          memory: 4096M
    stdin_open: true
    tty: true
    env_file:
      - ./miam.env
    logging: *default-logging
    restart: unless-stopped    

  gaming-minecraft-lycee:
    container_name: ${MINECRAFT_LYCEE_CONTAINER_NAME}
    image: itzg/minecraft-server
    ports:
      - ${MINECRAFT_LYCEE_PORT_EXTERNAL}:${MINECRAFT_LYCEE_PORT_INTERNAL}
    volumes:
     - ${ROOT_PROJECT_DATA_DIR}/${MINECRAFT_LYCEE_SAVE_PATH}:/data 
    environment:
      EULA: "TRUE"        
      ENABLE_RCON: "true" 
      RCON_PASSWORD: ${MINECRAFT_LYCEE_PASSWORD}
      RCON_PORT: ${MINECRAFT_LYCEE_RCON_INTERNAL}
      TYPE: "paper"
    restart: always 


  gaming-minecraft-stacia:
    container_name: ${MINECRAFT_STACIA_CONTAINER_NAME}
    image: itzg/minecraft-server
    ports:
      - ${MINECRAFT_STACIA_EXTERNAL_PORT}:${MINECRAFT_STACIA_INTERNAL_PORT}
    volumes:
      - ${ROOT_PROJECT_DATA_DIR}/${MINECRAFT_STACIA_SAVE_PATH}:/data
    environment:
      EULA: "TRUE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: ${MINECRAFT_STACIA_PASSWORD}
      RCON_PORT: ${MINECRAFT_STACIA_RCON_INTERNAL}
      MOD_PLATFORM: AUTO_CURSEFORGE
      CF_SLUG: stacia-2-expert
      CF_API_KEY: ${CF_API_KEY}
      MEMORY: 6G
    deploy:
      resources:
        limits:
          memory: 8G
    logging: *default-logging
    restart: unless-stopped

  gaming-minecraft-holycube:
    container_name: ${MINECRAFT_HOLYCUBE_CONTAINER_NAME}
    image: itzg/minecraft-server
    ports:
      - ${MINECRAFT_HOLYCUBE_EXTERNAL_PORT}:${MINECRAFT_HOLYCUBE_INTERNAL_PORT}
    volumes:
      - ${ROOT_PROJECT_DATA_DIR}/${MINECRAFT_HOLYCUBE_SAVE_PATH}:/data
    environment:
      EULA: "TRUE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: ${MINECRAFT_HOLYCUBE_PASSWORD}
      RCON_PORT: ${MINECRAFT_HOLYCUBE_RCON_INTERNAL}
      TYPE: NEOFORGE
      VERSION: "1.21.1"
      CF_SLUG: holycube-revolution
      CF_FILENAME_MATCHER: 1.0.5
      MOD_PLATFORM: AUTO_CURSEFORGE
      CF_API_KEY: ${CF_API_KEY}
      CURSEFORGE_FILES: |
        minecolonies
        structurize
        multi-piston
        blockui
        domum-ornamentum
      MEMORY: 6G
    deploy:
      resources:
        limits:
          memory: 8G
    logging: *default-logging
    restart: unless-stopped

  gaming-minecraft-holycube-max:
    container_name: ${MINECRAFT_HOLYCUBE_MAX_CONTAINER_NAME}
    image: itzg/minecraft-server
    ports:
      - ${MINECRAFT_HOLYCUBE_MAX_EXTERNAL_PORT}:${MINECRAFT_HOLYCUBE_MAX_INTERNAL_PORT}
    volumes:
      - ${ROOT_PROJECT_DATA_DIR}/${MINECRAFT_HOLYCUBE_MAX_SAVE_PATH}:/data
    environment:
      EULA: "TRUE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: ${MINECRAFT_HOLYCUBE_MAX_PASSWORD}
      RCON_PORT: ${MINECRAFT_HOLYCUBE_MAX_RCON_INTERNAL}
      TYPE: AUTO_CURSEFORGE
      VERSION: "1.21.1"
      CF_SLUG: holycube-revolution
      CF_EXCLUDE_MODS: |
        particular-reforged
        wakes-reforged
        smithing-template-viewer
      CF_API_KEY: ${CF_API_KEY}
      MEMORY: 6G
    deploy:
      resources:
        limits:
          memory: 8G
    logging: *default-logging
    restart: unless-stopped

  gaming-minecraft-ozone3:
    container_name: ${MINECRAFT_OZONE3_CONTAINER_NAME}
    image: itzg/minecraft-server:java8-multiarch
    ports:
      - ${MINECRAFT_OZONE3_EXTERNAL_PORT}:${MINECRAFT_OZONE3_INTERNAL_PORT}
    volumes:
      - ${ROOT_PROJECT_DATA_DIR}/${MINECRAFT_OZONE3_SAVE_PATH}:/data
    environment:
      EULA: "TRUE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: ${MINECRAFT_OZONE3_RCON_PASSWORD}
      RCON_PORT: ${MINECRAFT_OZONE3_RCON_INTERNAL}
      TYPE: AUTO_CURSEFORGE
      VERSION: "1.12.2"
      JAVA_VERSION: 8
      CF_SLUG: project-ozone-3-a-new-way-forward
      CF_API_KEY: ${CF_API_KEY}
      MEMORY: ${MINECRAFT_OZONE3_MEMORY}
      # Facultatif : exclusion de mods
      CF_MODS: "253449"
      #Options recommandées :
      PACK_MODE: ${MINECRAFT_OZONE3_PACKMODE}
      LEVEL_TYPE: botania-skyblock
    deploy:
      resources:
        limits:
          memory: ${MINECRAFT_OZONE3_MEMORY_LIMIT}
    logging: *default-logging
    restart: unless-stopped