#Principale Network Configuration

networks:
  default:
    name: schub_network
    ipam:
      config:
        - subnet: 172.20.0.0/16

#Log Configuration

x-logging:
  &default-logging
  driver: "json-file"
  options:
    tag: "{{.Name}}"

#Container Configuration

services:

  admin-portainer:
    container_name: ${PORTAINER_CONTAINER_NAME}
    image: portainer/portainer-be:latest
    ports:
      - ${PORTAINER_EXTERNAL_PORT}:${PORTAINER_INTERNAL_PORT}
    volumes:
      - ${ROOT_PROJECT_DATA_DIR}/${PORTAINER_SAVE_PATH}:/data
      - ${PORTAINER_DOCKER_SOCKET}:${PORTAINER_DOCKER_SOCKET}
    environment:
      - VIRTUAL_HOST=${PORTAINER_VIRTUAL_HOST}
      - VIRTUAL_PORT=${PORTAINER_VIRTUAL_PORT}
    command: -H unix:///var/run/docker.sock
    logging: *default-logging
    restart: always

  admin-code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: ${CODE_SERVER_CONTAINER_NAME}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - PASSWORD=${CODE_SERVER_PASSWORD}
    volumes:
      - ${ROOT_PROJECT_DATA_DIR}/${CODE_SERVER_CONFIG_PATH}:/config
      - ${ROOT_DATA_DIR}:/home/coder/project
    ports:
      - ${CODE_SERVER_EXTERNAL_PORT}:8443
    restart: unless-stopped
    logging: *default-logging
  
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: ${HOMEPAGE_CONTAINER_NAME}
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=homepage.schultz-thomas.fr
    ports:
      - ${HOMEPAGE_SERVER_EXTERNAL_PORT}:3000
    volumes:
      - ${ROOT_PROJECT_DATA_DIR}/${HOMEPAGE_SERVER_CONFIG_PATH}:/app/config 
      - ${PORTAINER_DOCKER_SOCKET}:${PORTAINER_DOCKER_SOCKET}
    restart: unless-stopped
    logging: *default-logging

  