#Principale Network Configuration

networks:
  default:
    name: schub_network
    ipam:
      config:
        - subnet: 172.20.0.0/16

#Log Configuration

x-logging:
  &default-logging
  driver: "json-file"
  options:
    tag: "{{.Name}}"

#Container Configuration

services:

  admin-portainer:
    container_name: ${PORTAINER_CONTAINER_NAME}
    image: portainer/portainer-ce:latest
    ports:
      - ${PORTAINER_EXTERNAL_PORT}:${PORTAINER_INTERNAL_PORT}
    volumes:
      - ${ROOT_PROJECT_DATA_DIR}/${PORTAINER_SAVE_PATH}:/data
      - ${PORTAINER_DOCKER_SOCKET}:${PORTAINER_DOCKER_SOCKET}
    environment:
      - VIRTUAL_HOST=${PORTAINER_VIRTUAL_HOST}
      - VIRTUAL_PORT=${PORTAINER_VIRTUAL_PORT}
    command: -H unix:///var/run/docker.sock
    logging: *default-logging
    restart: always