version: '3.8'

# Volumes

volumes:
  homepage_config:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume/Homepage/Config
      o: bind

# Log Configuration

x-logging:
  &default-logging
  driver: "json-file"
  options:
    tag: "{{.Name}}"

# Services

services:

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    networks:
      - schub
    volumes:
      - homepage_config:/app/config 
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homepage.schultz-thomas.fr
    logging: *default-logging
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.name == dynamis

# Networks

networks:
  schub:
    external: true

  