version: '3.8'

# Volumes

volumes:
  sonarr_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/volume/Sonarr

  radarr_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/volume/Radarr

  jellyfin_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/volume/Jellyfin/config

  jellyfin_cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/volume/Jellyfin/cache

  media:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/media/media

  media_series:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/media/media/series

  media_movies:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/media/media/movie

  media_downloads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/media/download

# Log Configuration

x-logging:
  &default-logging
  driver: "json-file"
  options:
    tag: "{{.Name}}"

# Services

services:

  media-sonarr:
    image: linuxserver/sonarr:4.0.19.2979-ls322
    networks:
      - schub
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
    volumes:
      - sonarr_config:/config
      - media_series:/tv
      - media_downloads:/downloads
    logging: *default-logging
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.name == dynamis

  media-radarr:
    image: linuxserver/radarr:6.3.0.10514-ls314
    networks:
      - schub
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
    volumes:
      - radarr_config:/config
      - media_movies:/movies
      - media_downloads:/downloads
    logging: *default-logging
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.name == dynamis

  media-jellyfin:
    image: jellyfin/jellyfin:10.11.11
    networks:
      - schub
    environment:
      TZ: Europe/Paris
    volumes:
      - jellyfin_data:/config
      - jellyfin_cache:/cache
      - media:/media:ro
    logging: *default-logging
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.name == dynamis

# Networks

networks:
  schub:
    external: true